### ISSUE TITLE
Gramex command returning error in windows

### ISSUE THREAD

**Issue by amanintech** [gramener/gramex#260]
I have done all the installation steps as told in the guide but this still doesn't work and returns the following error -

``` (base) D:\ML\PycharmProjects\gramex>gramex
INFO    15-Jul 15:18:01 __init__ PORT Gramex 1.61.1 | D:\ML\PycharmProjects\gramex | Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
DEBUG   15-Jul 15:18:01 config PORT Loading config: c:\python38\lib\site-packages\gramex\gramex.yaml
DEBUG   15-Jul 15:18:01 config PORT Loading config: D:\ML\PycharmProjects\gramex\gramex.yaml
DEBUG   15-Jul 15:18:01 __init__ PORT Loading service: version
DEBUG   15-Jul 15:18:01 __init__ PORT Loading service: mime
DEBUG   15-Jul 15:18:02 __init__ PORT Loading service: threadpool
DEBUG   15-Jul 15:18:02 __init__ PORT Loading service: cache
DEBUG   15-Jul 15:18:02 __init__ PORT Loading service: handlers
DEBUG   15-Jul 15:18:02 __init__ PORT Loading service: log
DEBUG   15-Jul 15:18:02 __init__ PORT Loading service: eventlog
DEBUG   15-Jul 15:18:02 __init__ PORT Loading service: app
Traceback (most recent call last):
  File "C:\Python38\Scripts\gramex-script.py", line 11, in <module>
    load_entry_point('gramex==1.61.1', 'console_scripts', 'gramex')()
  File "c:\python38\lib\site-packages\gramex\__init__.py", line 168, in commandline
    callback(**kwargs)
  File "c:\python38\lib\site-packages\gramex\__init__.py", line 276, in init
    callback = getattr(services, key)(conf[key])
  File "c:\python38\lib\site-packages\gramex\services\__init__.py", line 138, in app
    info.app.listen(**conf.listen)
  File "c:\python38\lib\site-packages\tornado\web.py", line 2042, in listen
    server.listen(port, address)
  File "c:\python38\lib\site-packages\tornado\tcpserver.py", line 144, in listen
    self.add_sockets(sockets)
  File "c:\python38\lib\site-packages\tornado\tcpserver.py", line 157, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "c:\python38\lib\site-packages\tornado\netutil.py", line 268, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "c:\python38\lib\site-packages\tornado\platform\asyncio.py", line 79, in add_handler
    self.asyncio_loop.add_reader(
  File "c:\python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError

```

**Comment by jaidevd** [comment]
@amanintech Please see this: https://github.com/gramener/gramex/issues/249, and see if it works, please.

**Comment by sanand0** [comment]
@amanintech -- as @jaidevd pointed out, you need Python 3.7. Tornado has a known bug in Python 3.8. Sorry about that.

**Comment by amanintech** [comment]
I have python 3.7.6 but it still returns the same error

**Comment by jaidevd** [comment]
Hi Aman, you have a call with @bkamapantula tomorrow, right? I'll join too
and we'll take a look at this.

**Comment by amanintech** [comment]
Sure

**Comment by jaidevd** [comment]
It was actually Python 3.8 that was causing this problem. There were two Python interpreters in the PATH, and Gramex was installed in Python 3.8
