### ISSUE TITLE
Builds fail installing R packages

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#317]
**Is something not working as expected?**
[Builds fail](https://travis-ci.com/github/gramener/gramex/builds/192620199) when running `gramex.ml.r('install.packages(...)')`

**Steps to reproduce.**
On a **fresh conda install**, run:

```python
import gramex.ml
gramex.ml.r('install.packages(c("rprojroot"))')
```

**Additional context**

This is because Microsoft CRAN seems to have an SSL certificate that requests cannot process.

```
>>> requests.get('https://cran.microsoft.com/src/contrib/PACKAGES')
Traceback (most recent call last):
  File "D:\anaconda\3.7\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "D:\anaconda\3.7\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "D:\anaconda\3.7\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "D:\anaconda\3.7\lib\site-packages\urllib3\connection.py", line 370, in connect
    ssl_context=context,
  File "D:\anaconda\3.7\lib\site-packages\urllib3\util\ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\anaconda\3.7\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "D:\anaconda\3.7\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "D:\anaconda\3.7\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\3.7\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\anaconda\3.7\lib\site-packages\urllib3\connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\anaconda\3.7\lib\site-packages\urllib3\util\retry.py", line 439, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cran.microsoft.com', port=443): Max retries exceeded with url: /src/contrib/PACKAGES (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFIC
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\anaconda\3.7\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "D:\anaconda\3.7\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\anaconda\3.7\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda\3.7\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda\3.7\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='cran.microsoft.com', port=443): Max retries exceeded with url: /src/contrib/PACKAGES (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))
```

**Solution**

- Replace default repo with a different [CRAN mirror](https://cran.r-project.org/mirrors.html), or
- At least do this in the test cases

**Comment by sanand0** [comment]
I will replace the default repo as `http://cran.r-project.org` in the next release.
