### ISSUE TITLE
Inserting datetime columns fails in Gramex >= 1.66

### ISSUE THREAD

**Issue by jaidevd** [gramener/gramex#356]
**Is something not working as expected?**
Inserting datetime objects into sqlite with `gramex.data.insert` works till v1.65, fails after that

**Steps to reproduce.**
Try this script:
```python
from datetime import timezone, datetime
from gramex.data import insert

url = "sqlite://"
now = datetime.now(timezone.utc).astimezone()
print(insert(url, table="foo", args={'time': [now]}))
```

**Expected behavior**
With gramex 1.65, it prints `1` as expected, and produces the following traceback on later versions:
```
/home/jaidevd/anaconda3/lib/python3.7/site-packages/pandas/core/missing.py:48: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask = arr == x
Traceback (most recent call last):
  File "foo.py", line 7, in <module>
    insert(url, table="foo", args={'time': [now]})
  File "/home/jaidevd/src/gramex/gramex/data.py", line 427, in insert
    rows.replace('', None, inplace=True)
  File "/home/jaidevd/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 4278, in replace
    method=method,
  File "/home/jaidevd/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 6637, in replace
    _single_replace, args=(to_replace, method, inplace, limit)
  File "/home/jaidevd/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 6928, in apply
    return op.get_result()
  File "/home/jaidevd/anaconda3/lib/python3.7/site-packages/pandas/core/apply.py", line 186, in get_result
    return self.apply_standard()
  File "/home/jaidevd/anaconda3/lib/python3.7/site-packages/pandas/core/apply.py", line 292, in apply_standard
    self.apply_series_generator()
  File "/home/jaidevd/anaconda3/lib/python3.7/site-packages/pandas/core/apply.py", line 321, in apply_series_generator
    results[i] = self.f(v)
  File "/home/jaidevd/anaconda3/lib/python3.7/site-packages/pandas/core/apply.py", line 112, in f
    return func(x, *args, **kwds)
  File "/home/jaidevd/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 111, in _single_replace
    if values.dtype == orig_dtype and inplace:
TypeError: ('data type not understood', 'occurred at index time')
```

**Comment by sanand0** [comment]
I'll take this for the next release (1.68 - 1 Feb)

**Comment by sanand0** [comment]
@jaidevd -- is this issue still occurring? I'm not able to reproduce it now.

**Comment by jaidevd** [comment]
Works now, @sanand0. Thanks!
