### ISSUE TITLE
Using version 1.66 ui.sass not converting to scss

### ISSUE THREAD

**Issue by AnjaliTonylijo** [gramener/gramex#362]
python version 3.7 
OS Windows

TraceBack

Traceback (most recent call last):                                                                                        File "C:\Users\anjali.menon\Anaconda3\envs\gramex\lib\site-packages\tornado\web.py", line 1592, in _execute               result = yield result                                                                                                 File "C:\Users\anjali.menon\Anaconda3\envs\gramex\lib\site-packages\tornado\gen.py", line 1133, in run                    value = future.result()                                                                                               File "C:\Users\anjali.menon\Anaconda3\envs\gramex\lib\site-packages\tornado\gen.py", line 1141, in run                    yielded = self.gen.throw(*exc_info)                                                                                   File "C:\Users\anjali.menon\Anaconda3\envs\gramex\lib\site-packages\gramex\handlers\functionhandler.py", line 60, in _get                                                                                                                         item = yield item                                                                                                     File "C:\Users\anjali.menon\Anaconda3\envs\gramex\lib\site-packages\tornado\gen.py", line 1133, in run                    value = future.result()                                                                                               File "C:\Users\anjali.menon\Anaconda3\envs\gramex\lib\site-packages\tornado\gen.py", line 1147, in run                    yielded = self.gen.send(value)                                                                                        File "C:\Users\anjali.menon\Anaconda3\envs\gramex\lib\site-packages\gramex\apps\ui\__init__.py", line 73, in sass         raise RuntimeError('Compilation failure')                                                                           RuntimeError: Compilation failure      

this occurs for endpoint
  pattern: /$YAMLURL/style.css
in gramex.yaml

**Comment by bhatsandeep** [comment]
Hi Anjali,

This is fixed in 1.67. Could you please upgrade to 1.67 and let us know if
the issue persists.

Regards
Sandeep

**Comment by AnjaliTonylijo** [comment]
I had installed using conda as in the gramex guide. When I tried updating gramex  using conda update gramex
I am getting the error
PackageNotInstalledError: Package is not installed in prefix.
prefix: C:\ProgramData\Anaconda3
package name: gramex

Also unable to run gramex without first running conda activate gramex each time from cmd

**Comment by jaidevd** [comment]
@AnjaliTonylijo 

Anything that needs to be done with Gramex, including running and updating it, has to be done after activating the correct environment, in your case, this is 

`conda activate gramex`

This cannot be avoided. Please update Gramex after running this command and let us know if it fixes the issue.

**Comment by jaidevd** [comment]
@bhatsandeep  - FYI, @AnjaliTonylijo and I are trying to update Gramex, and apparently `conda update gramex` _doesn't_ update gramex at all... I'm trying to reproduce this and debug it.

**Comment by jaidevd** [comment]
This can be closed when gramener/gramex-guide#50 is merged.
