### ISSUE TITLE
GRAMEX-151 ⁃ Gramex service does not start on Conda - Python 3.9 - Custom environment

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#498]
On the latest Anaconda version -- Python 3.9.7, Gramex 1.76.0, conda 4.10.3, with Gramex installed in a `gramex` conda environment:

Create this `gramex.yaml`

```yaml
url:
  home:
    pattern: /
    handler: FunctionHandler
    kwargs:
      function: f'Hello world'
```

Run:

```shell
gramex service install
gramex service start
```

This creates the following error in the Windoes Event Viewer > Windows Logs > Application:

```
The GramexApp service has stopped
Traceback (most recent call last):
  File "D:\anaconda\3.9\envs\gramex\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "D:\anaconda\3.9\envs\gramex\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "D:\anaconda\3.9\envs\gramex\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\site\gramener.com\viz\async-gramex\gramex\winservice.py", line 76, in SvcDoRun
    gramex.commandline(None if port is None else [f'--listen.port={port}'])
  File "d:\site\gramener.com\viz\async-gramex\gramex\__init__.py", line 171, in commandline
    callback, kwargs = callback_commandline(sys.argv[1:] if args is None else args)
  File "d:\site\gramener.com\viz\async-gramex\gramex\__init__.py", line 119, in callback_commandline
    from . import services
  File "d:\site\gramener.com\viz\async-gramex\gramex\services\__init__.py", line 29, in <module>
    import gramex.data
  File "d:\site\gramener.com\viz\async-gramex\gramex\data.py", line 11, in <module>
    import numpy as np
  File "D:\anaconda\3.9\envs\gramex\lib\site-packages\numpy\__init__.py", line 150, in <module>
    from . import core
  File "D:\anaconda\3.9\envs\gramex\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "D:\anaconda\3.9\envs\gramex\lib\site-packages\win32\PythonService.exe"
  * The NumPy version is: "1.21.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.
```

┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-151)

**Comment by sanand0** [comment]
Fixed by 585af8a8
