### ISSUE TITLE
Gramex tests indicate torch is required

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#558]
`nosetests` reports this error:

```
tornado.application: ERROR: Uncaught exception GET /sentiment?text=This%20is%20bad.&text=This%20is%20good. (::1)
HTTPServerRequest(protocol='http', host='localhost:9999', method='GET', uri='/sentiment?text=This%20is%20bad.&text=This%20is%20good.', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "C:\Users\Anand S\.conda\envs\gramex\lib\site-packages\tornado\web.py", line 1704, in _execute
    result = await result
  File "C:\Users\Anand S\.conda\envs\gramex\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "C:\site\gramener.com\viz\async-gramex\gramex\handlers\mlhandler.py", line 242, in get
    self._check_model_path()
  File "C:\site\gramener.com\viz\async-gramex\gramex\handlers\mlhandler.py", line 211, in _check_model_path
    self.model = locate(wrapper).from_disk(self.store.model_path, klass=klass)
  File "C:\site\gramener.com\viz\async-gramex\gramex\ml_api.py", line 411, in from_disk
    return cls(klass(model, tokenizer))
  File "C:\site\gramener.com\viz\async-gramex\gramex\transformers.py", line 32, in __init__
    trf.AutoModelForSequenceClassification, model, DEFAULT_MODEL
  File "C:\site\gramener.com\viz\async-gramex\gramex\transformers.py", line 23, in load_pretrained
    model = klass.from_pretrained(default, **kwargs)
  File "C:\Users\Anand S\.conda\envs\gramex\lib\site-packages\transformers\utils\import_utils.py", line 821, in __getattr__
    requires_backends(cls, cls._backends)
  File "C:\Users\Anand S\.conda\envs\gramex\lib\site-packages\transformers\utils\import_utils.py", line 809, in requires_backends
    raise ImportError("".join(failed))
ImportError:
AutoModelForSequenceClassification requires the PyTorch library but it was not found in your environment. Checkout the instructions on the
installation page: https://pytorch.org/get-started/locally/ and follow the ones that match your environment.
```

`torch` is not a specific requirement in our test cases. Should it be, @jaidevd?

**Comment by jaidevd** [comment]
I thought skipping the tests might suffice, but `tests/gramex.yaml` still run. In addition to skipping the tests, `MLHandler` should log an import exception and Gramex should keep running.

I'll send a fix which does this.

**Comment by sanand0** [comment]
Resolved.
