### ISSUE TITLE
MLHandler template raises an error when retraining

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#603]
Note: model= appears empty even when we retrain with a specific model

![image](https://user-images.githubusercontent.com/63734/192216460-3453ecce-ee62-4269-88fb-134f7ef0b92f.png)

Console log error:

```
Uncaught SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.success (ml:401:36)
    at c (jquery.min.js:2:28327)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:29072)
    at l (jquery.min.js:2:79901)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82355)
```

**Comment by jaidevd** [comment]
@sanand0 you noticed this on the IDE? Or did it happen when running Gramex yourself?

**Comment by sanand0** [comment]
I ran Gramex locally, not the IDE, @jaidevd
