### ISSUE TITLE
Getting the error when I start gramex locally

### ISSUE THREAD

**Issue by s-jaiprakash** [gramener/gramex#785]
**Is something not working as expected?**
Unable to run gramex locally

**Steps to reproduce.**
- Step 1: Install gramex using the steps listed [here](https://gramener.com/gramex/guide/install/#conda-install)
- Step 2: Run gramex using the steps given [here](https://gramener.com/gramex/guide/install/#run-a-gramex-app)

```bash
(gramex) C:\Users\e430284\Downloads\test>gramex
INFO    06-Aug 14:43:46 gramex:__init__ PORT Gramex 1.94.3 | C:\Users\e430284\Downloads\test | Python 3.9.19 (main, May  6 2024, 20:12:36) [MSC v.1916 64 bit (AMD64)]
DEBUG   06-Aug 14:43:46 gramex:__init__ PORT Loading service: eventlog
DEBUG   06-Aug 14:43:46 gramex:__init__ PORT Loading service: app
DEBUG   06-Aug 14:43:46 gramex:__init__ PORT Loading service: storelocations
DEBUG   06-Aug 14:43:46 gramex:__init__ PORT Loading service: schedule
INFO    06-Aug 14:43:46 gramex:__init__ PORT Initialising schedule:gramex_update
DEBUG   06-Aug 14:43:46 gramex:scheduler PORT schedule:gramex_update: Next run in 33373.3s
INFO    06-Aug 14:43:46 gramex:__init__ PORT Initialising schedule:gramex_purge_otp
DEBUG   06-Aug 14:43:46 gramex:scheduler PORT schedule:gramex_purge_otp: Next run in 33433.3s
DEBUG   06-Aug 14:43:46 gramex:__init__ PORT Gramex update ran recently. Deferring check.
INFO    06-Aug 14:43:46 gramex:__init__ PORT Initialising schedule:gramex_migrate
DEBUG   06-Aug 14:43:46 gramex:__init__ PORT Loading service: url
DEBUG   06-Aug 14:43:46 gramex:transforms PORT pipeline:schedule:gramex_migrate running
DEBUG   06-Aug 14:43:46 gramex:__init__ PORT url:apps/ui/theme-Aa7xp (FileHandler)
DEBUG   06-Aug 14:43:46 gramex:migrate PORT 1.87.0: SKIP migrated storelocations.user.url: C:/Users/e430284/AppData/Local/Gramex Data/auth.user.db
C:\Users\e430284\AppData\Local\anaconda3\envs\gramex\lib\site-packages\gramex\data.py:601: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  rows[col].replace({'': None}, inplace=True)
C:\Users\e430284\AppData\Local\anaconda3\envs\gramex\lib\site-packages\gramex\data.py:604: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.io.sql.to_sql(
ERROR   06-Aug 14:43:46 gramex:transforms PORT pipeline:schedule:gramex_migrate exception logging failed
Traceback (most recent call last):
  File "C:\Users\e430284\AppData\Local\anaconda3\envs\gramex\lib\site-packages\gramex\transforms\transforms.py", line 447, in run_pipeline
    insert(
  File "C:\Users\e430284\AppData\Local\anaconda3\envs\gramex\lib\site-packages\gramex\data.py", line 604, in insert
    pd.io.sql.to_sql(
  File "C:\Users\e430284\AppData\Local\anaconda3\envs\gramex\lib\site-packages\pandas\io\sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
  File "C:\Users\e430284\AppData\Local\anaconda3\envs\gramex\lib\site-packages\pandas\io\sql.py", line 2850, in to_sql
    table.create()
  File "C:\Users\e430284\AppData\Local\anaconda3\envs\gramex\lib\site-packages\pandas\io\sql.py", line 984, in create
    if self.exists():
  File "C:\Users\e430284\AppData\Local\anaconda3\envs\gramex\lib\site-packages\pandas\io\sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
  File "C:\Users\e430284\AppData\Local\anaconda3\envs\gramex\lib\site-packages\pandas\io\sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
  File "C:\Users\e430284\AppData\Local\anaconda3\envs\gramex\lib\site-packages\pandas\io\sql.py", line 2672, in execute
    cur = self.con.cursor()
AttributeError: 'Engine' object has no attribute 'cursor'
INFO    06-Aug 14:43:46 gramex:ml PORT gramex.ml.TopCause not imported. pip install sklearn
DEBUG   06-Aug 14:43:47 gramex:config PORT Loading config: C:\Users\e430284\AppData\Local\anaconda3\envs\gramex\lib\site-packages\gramex\apps.yaml
WARNING 06-Aug 14:43:47 gramex:__init__ PORT url: MLHandler/MLPredictor dependency missing. No module named 'sklearn'
DEBUG   06-Aug 14:43:47 gramex:__init__ PORT url:test-login (SimpleAuth)
DEBUG   06-Aug 14:43:47 gramex:__init__ PORT url:test-logout (LogoutHandler)
DEBUG   06-Aug 14:43:47 gramex:__init__ PORT url:apps/ui/bootstrap4-NLpk0 (FunctionHandler)
DEBUG   06-Aug 14:43:47 gramex:__init__ PORT url:apps/ui/static-93NBa (FunctionHandler)
DEBUG   06-Aug 14:43:47 gramex:__init__ PORT url:test-home (FileHandler)
DEBUG   06-Aug 14:43:47 gramex:__init__ PORT url:favicon (FileHandler) -90
DEBUG   06-Aug 14:43:47 gramex:__init__ PORT url:default (FileHandler) -100
DEBUG   06-Aug 14:43:47 gramex:__init__ PORT Running callback: app
INFO    06-Aug 14:43:47 gramex:__init__ PORT Listening on port 9988
Gramex 1.94.3 listening on http://127.0.0.1:9988/. <Ctrl-B> opens browser, <Ctrl-D> starts debugger
INFO    06-Aug 14:44:06 gramex:__init__ 9988 Shutting down Gramex...
```

**Expected behavior:**
It should work without any errors

**Your environment:**

- OS: Windows
- Browser: Chrome
- Python version: 3.9.19
- Gramex version: 1.94.3

**Comment by jpsiyyadri** [comment]
I have tried to debug the issue and identified the issue is between Pandas 2.2 and SQLAlchemy 1.4.53 [reference](https://github.com/pandas-dev/pandas/issues/57049)

Resolution:

```bash
pip install pandas==2.1.4
```

Issue is resolved!

**Comment by jaidevd** [comment]
Thanks, @s-jaiprakash 

With `pandas==2.1.4`, the sqlalchemy version also needs to be pinned,

```bash
pip install pandas==2.1.4 sqlalchemy==1.4.36
```
